# Generated by Django 3.0.5 on 2021-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app14', '0002_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistation',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cno', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('rdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
